### ISSUE TITLE
ModuleNotFoundError: No module named 'TeenStudy'

### ISSUE THREAD

**Issue by Conkinya** [YouthLearning/TeenStudy#22]
启动时日志
05-19 10:29:45 [ERROR] nonebot | Failed to import "TeenStudy"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'TeenStudy'

**Comment by Conkinya** [comment]
安装时日志
Administrator@hcss-ecs-529f MINGW64 ~/Desktop/Nonebot/Nonebot-ciallo
$ nb plugin install TeenStudy
ʹ▒▒ Python: C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Scripts\python.exe
WARNING: Skipping C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot_plugin_apscheduler-0.4.0.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot_plugin_apscheduler-0.4.0.dist-info due to invalid metadata entry 'name'
Collecting teenstudy
  Using cached teenstudy-0.2.6-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: Jinja2<4.0.0,>=3.1.2 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from teenstudy) (3.1.3)
Collecting amis-python<2.0.0,>=1.0.8 (from teenstudy)
  Using cached amis_python-1.0.8.post2-py3-none-any.whl.metadata (2.4 kB)
Collecting anti-useragent<2.0.0,>=1.0.10 (from teenstudy)
  Using cached anti_useragent-1.0.10-py3-none-any.whl.metadata (4.4 kB)
Collecting beautifulsoup4<5.0.0,>=4.11.2 (from teenstudy)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bs4<0.0.2,>=0.0.1 (from teenstudy)
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting ddddocr<2.0.0,>=1.4.7 (from teenstudy)
  Using cached ddddocr-1.5.3-py3-none-any.whl.metadata (16 kB)
Collecting fastapi<0.101.0,>=0.100.0 (from teenstudy)
  Using cached fastapi-0.100.1-py3-none-any.whl.metadata (23 kB)
Collecting httpx<0.25.0,>=0.24.0 (from teenstudy)
  Using cached httpx-0.24.1-py3-none-any.whl.metadata (7.4 kB)
Collecting lxml<5.0.0,>=4.9.2 (from teenstudy)
  Using cached lxml-4.9.4-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: nonebot-adapter-onebot<3.0.0,>=2.2.3 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from teenstudy) (2.4.3)
Collecting nonebot-plugin-apscheduler<0.4.0,>=0.3.0 (from teenstudy)
  Using cached nonebot_plugin_apscheduler-0.3.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: nonebot2<3.0.0,>=2.0.0 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from teenstudy) (2.3.0)
Requirement already satisfied: psutil<6.0.0,>=5.9.4 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from teenstudy) (5.9.8)
Collecting pycryptodome<4.0,>=3.17 (from teenstudy)
  Using cached pycryptodome-3.20.0-cp35-abi3-win_amd64.whl.metadata (3.4 kB)
Collecting python-jose<4.0.0,>=3.3.0 (from teenstudy)
  Using cached python_jose-3.3.0-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting qrcode<8.0.0,>=7.4.2 (from teenstudy)
  Using cached qrcode-7.4.2-py3-none-any.whl.metadata (17 kB)
Collecting tortoise-orm<0.20.0,>=0.19.3 (from teenstudy)
  Using cached tortoise_orm-0.19.3-py3-none-any.whl.metadata (10 kB)
Collecting ujson<6.0.0,>=5.7.0 (from teenstudy)
  Using cached ujson-5.10.0-cp312-cp312-win_amd64.whl.metadata (9.5 kB)
Collecting uvicorn<0.22.0,>=0.21.0 (from teenstudy)
  Using cached uvicorn-0.21.1-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: pydantic<2.0.0,>=1.9.2 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from amis-python<2.0.0,>=1.0.8->teenstudy) (1.10.15)
Requirement already satisfied: loguru in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from anti-useragent<2.0.0,>=1.0.10->teenstudy) (0.7.2)
Collecting soupsieve>1.2 (from beautifulsoup4<5.0.0,>=4.11.2->teenstudy)
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: numpy in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from ddddocr<2.0.0,>=1.4.7->teenstudy) (1.26.4)
Collecting onnxruntime (from ddddocr<2.0.0,>=1.4.7->teenstudy)
  Using cached onnxruntime-1.18.0-cp312-cp312-win_amd64.whl.metadata (4.4 kB)
Requirement already satisfied: Pillow in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from ddddocr<2.0.0,>=1.4.7->teenstudy) (10.3.0)
Collecting opencv-python-headless (from ddddocr<2.0.0,>=1.4.7->teenstudy)
  Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting starlette<0.28.0,>=0.27.0 (from fastapi<0.101.0,>=0.100.0->teenstudy)
  Using cached starlette-0.27.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from fastapi<0.101.0,>=0.100.0->teenstudy) (4.11.0)
Requirement already satisfied: certifi in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from httpx<0.25.0,>=0.24.0->teenstudy) (2024.2.2)
Collecting httpcore<0.18.0,>=0.15.0 (from httpx<0.25.0,>=0.24.0->teenstudy)
  Using cached httpcore-0.17.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: idna in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from httpx<0.25.0,>=0.24.0->teenstudy) (3.7)
Requirement already satisfied: sniffio in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from httpx<0.25.0,>=0.24.0->teenstudy) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from Jinja2<4.0.0,>=3.1.2->teenstudy) (2.1.5)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from nonebot-adapter-onebot<3.0.0,>=2.2.3->teenstudy) (1.0.8)
Requirement already satisfied: apscheduler<4.0.0,>=3.7.0 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from nonebot-plugin-apscheduler<0.4.0,>=0.3.0->teenstudy) (3.10.4)
Requirement already satisfied: pygtrie<3.0.0,>=2.4.1 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from nonebot2<3.0.0,>=2.0.0->teenstudy) (2.5.0)
Requirement already satisfied: python-dotenv<2.0.0,>=0.21.0 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from nonebot2<3.0.0,>=2.0.0->teenstudy) (1.0.1)
Requirement already satisfied: yarl<2.0.0,>=1.7.2 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from nonebot2<3.0.0,>=2.0.0->teenstudy) (1.9.4)
Collecting ecdsa!=0.15 (from python-jose<4.0.0,>=3.3.0->teenstudy)
  Using cached ecdsa-0.19.0-py2.py3-none-any.whl.metadata (29 kB)
Collecting rsa (from python-jose<4.0.0,>=3.3.0->teenstudy)
  Using cached rsa-4.9-py3-none-any.whl.metadata (4.2 kB)
Collecting pyasn1 (from python-jose<4.0.0,>=3.3.0->teenstudy)
  Using cached pyasn1-0.6.0-py2.py3-none-any.whl.metadata (8.3 kB)
Collecting pypng (from qrcode<8.0.0,>=7.4.2->teenstudy)
  Using cached pypng-0.20220715.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: colorama in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from qrcode<8.0.0,>=7.4.2->teenstudy) (0.4.6)
Collecting aiosqlite<0.18.0,>=0.16.0 (from tortoise-orm<0.20.0,>=0.19.3->teenstudy)
  Using cached aiosqlite-0.17.0-py3-none-any.whl.metadata (4.1 kB)
Collecting iso8601<2.0.0,>=1.0.2 (from tortoise-orm<0.20.0,>=0.19.3->teenstudy)
  Using cached iso8601-1.1.0-py3-none-any.whl.metadata (9.8 kB)
Collecting pypika-tortoise<0.2.0,>=0.1.6 (from tortoise-orm<0.20.0,>=0.19.3->teenstudy)
  Using cached pypika_tortoise-0.1.6-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: pytz in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from tortoise-orm<0.20.0,>=0.19.3->teenstudy) (2024.1)
Requirement already satisfied: click>=7.0 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from uvicorn<0.22.0,>=0.21.0->teenstudy) (8.1.7)
Requirement already satisfied: h11>=0.8 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from uvicorn<0.22.0,>=0.21.0->teenstudy) (0.14.0)
Requirement already satisfied: six>=1.4.0 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from apscheduler<4.0.0,>=3.7.0->nonebot-plugin-apscheduler<0.4.0,>=0.3.0->teenstudy) (1.16.0)
Requirement already satisfied: tzlocal!=3.*,>=2.0 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from apscheduler<4.0.0,>=3.7.0->nonebot-plugin-apscheduler<0.4.0,>=0.3.0->teenstudy) (5.2)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx<0.25.0,>=0.24.0->teenstudy) (4.3.0)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from loguru->anti-useragent<2.0.0,>=1.0.10->teenstudy) (1.1.0)
Requirement already satisfied: multidict>=4.0 in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from yarl<2.0.0,>=1.7.2->nonebot2<3.0.0,>=2.0.0->teenstudy) (6.0.5)
Collecting coloredlogs (from onnxruntime->ddddocr<2.0.0,>=1.4.7->teenstudy)
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting flatbuffers (from onnxruntime->ddddocr<2.0.0,>=1.4.7->teenstudy)
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
Requirement already satisfied: packaging in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from onnxruntime->ddddocr<2.0.0,>=1.4.7->teenstudy) (24.0)
Collecting protobuf (from onnxruntime->ddddocr<2.0.0,>=1.4.7->teenstudy)
  Using cached protobuf-5.26.1-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Collecting sympy (from onnxruntime->ddddocr<2.0.0,>=1.4.7->teenstudy)
  Using cached sympy-1.12-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: tzdata in c:\users\administrator\desktop\nonebot\nonebot-ciallo\.venv\lib\site-packages (from tzlocal!=3.*,>=2.0->apscheduler<4.0.0,>=3.7.0->nonebot-plugin-apscheduler<0.4.0,>=0.3.0->teenstudy) (2024.1)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime->ddddocr<2.0.0,>=1.4.7->teenstudy)
  Using cached humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting mpmath>=0.19 (from sympy->onnxruntime->ddddocr<2.0.0,>=1.4.7->teenstudy)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting pyreadline3 (from humanfriendly>=9.1->coloredlogs->onnxruntime->ddddocr<2.0.0,>=1.4.7->teenstudy)
  Using cached pyreadline3-3.4.1-py3-none-any.whl.metadata (2.0 kB)
Using cached teenstudy-0.2.6-py3-none-any.whl (6.4 MB)
Using cached amis_python-1.0.8.post2-py3-none-any.whl (58 kB)
Using cached anti_useragent-1.0.10-py3-none-any.whl (25 kB)
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Downloading ddddocr-1.5.3-py3-none-any.whl (75.9 MB)
   --------------------                     38.4/75.9 MB 978.6 kB/s eta 0:00:39
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 479, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1252, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1104, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 179, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 552, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 467, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_internal\network\download.py", line 183, in __call__
    for chunk in chunks:
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    with self._error_catcher():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
WARNING: Skipping C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot_plugin_apscheduler-0.4.0.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot_plugin_apscheduler-0.4.0.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot_plugin_apscheduler-0.4.0.dist-info due to invalid metadata entry 'name'
